#include <std_include.hpp>
#include "engine_scene_completion.hpp"
#include "engine_scene_job_capture.hpp"
#include "loader/target_identity.hpp"
#include "component/console.hpp"
#include <utils/hook_validation.hpp>

namespace vr::engine_scene_completion
{
	namespace
	{
		constexpr std::uintptr_t backend_frontend = 0x151A7F3B0;
		constexpr std::uintptr_t wait_function = 0x140793DE0;
		constexpr std::array<std::uintptr_t, 3> predicates{0x1407A7190, 0x1407A71F0, 0x1407A71C0};
		std::atomic_uint64_t attempts{}, completions{}, failures{}, pending{};
		std::atomic<failure> last_failure{};
		flags read_flags(std::uintptr_t frontend) noexcept
		{
			const auto* fields = reinterpret_cast<const volatile std::uint32_t*>(frontend + 0x541BE8);
			return {fields[0], fields[1], fields[2], fields[3]};
		}
		template<std::size_t N>
		void require_bytes(std::uintptr_t address, const std::array<std::uint8_t, N>& bytes)
		{
			std::array<std::uint8_t, N> mask;
			mask.fill(0xFF);
			if (!utils::hook_validation::validate_executable_target(reinterpret_cast<void*>(address)) ||
				!utils::hook_validation::verify_masked_bytes(reinterpret_cast<void*>(address),
					{bytes.data(), mask.data(), N}))
				throw std::runtime_error("H2 CPU scene completion ABI mismatch");
		}
	}

	void validate()
	{
		if (!target_identity::get().compatibility_probe_passed)
			throw std::runtime_error("H2 CPU scene completion requires verified image");
		require_bytes(wait_function, std::array<std::uint8_t, 14>{
			0x40,0x55,0x41,0x57,0x48,0x83,0xEC,0x38,0x44,0x8B,0xFA,0x48,0x8B,0xE9});
		// Verify each predicate's exact global, completion offset and slow path.
		for (std::size_t i{}; i < predicates.size(); ++i)
		{
			std::array<std::uint8_t, 43> bytes{
				0x48,0x83,0xEC,0x28,0x48,0x8B,0x05,0,0,0,0,
				0x8B,0x88,0,0,0,0,0x85,0xC9,0x74,0x0A,0xB8,0x01,0,0,0,
				0x48,0x83,0xC4,0x28,0xC3,0xE8,0,0,0,0,0x33,0xC0,0x48,0x83,0xC4,0x28,0xC3};
			const auto global_delta = static_cast<std::int32_t>(backend_frontend - (predicates[i] + 11));
			const std::array<std::uint32_t, 3> offsets{0x541BE8, 0x541BF0, 0x541BF4};
			const auto slow_delta = static_cast<std::int32_t>(0x14079A3C0 - (predicates[i] + 36));
			std::memcpy(bytes.data()+7, &global_delta, 4);
			std::memcpy(bytes.data()+13, &offsets[i], 4);
			std::memcpy(bytes.data()+32, &slow_delta, 4);
			require_bytes(predicates[i], bytes);
		}
	}

	bool await(std::uintptr_t frontend, const void* record) noexcept
	{
		attempts.fetch_add(1, std::memory_order_relaxed);
		region_capture::phase_scope timing(region_capture::phase::scene_completion, record, frontend);
		const auto identity = [] { return *reinterpret_cast<const volatile std::uintptr_t*>(backend_frontend); };
		if (frontend && identity() == frontend && !read_flags(frontend).complete())
			pending.fetch_add(1, std::memory_order_relaxed);
		// Stage-0..3 job 0x1B is queued by the original frontend generator.
		// The same generator drains it via 0x140794200 before returning. It is
		// CPU input production, not a completion signal generated by eye rendering.
		// Preserve H2's predicates (including renderer synchronization) and job
		// pumping; original owner waits remain and now observe ready inputs.
		const auto error = await_inputs(frontend, identity, [](stage point)
		{
			reinterpret_cast<std::uintptr_t(*)(void*, std::uint32_t)>(wait_function)(
				reinterpret_cast<void*>(predicates[static_cast<std::size_t>(point)]), 1);
		}, read_flags);
		if (error != failure::none)
		{
			last_failure.store(error, std::memory_order_release);
			if (failures.fetch_add(1, std::memory_order_relaxed) == 0)
				console::error("[VR] CPU scene completion rejected (reason=%u); stereo snapshot not created\n",
					static_cast<unsigned>(error));
			return false;
		}
		std::atomic_thread_fence(std::memory_order_acquire);
		completions.fetch_add(1, std::memory_order_relaxed);
		engine_scene_job_capture::checkpoint(record, frontend, region_capture::phase::scene_completion);
		timing.finish(1);
		return true;
	}

	status get_status() noexcept
	{
		return {attempts.load(), completions.load(), failures.load(), pending.load(), last_failure.load()};
	}
}
