-- Product version is explicit and works in source snapshots without Git history.
-- Git metadata remains diagnostic provenance, never the displayed release name.
local decode_json = json.decode -- deps/premake/json.lua later owns the global 'json'.
local function release_version()
	local file = assert(io.open(path.join(_MAIN_SCRIPT_DIR, "version.json"), "rb"))
	local value = decode_json(file:read("*a"))
	file:close()
	assert(type(value.name) == "string" and #value.name > 0 and #value.name <= 64, "Invalid release name")
	assert(type(value.file_version) == "table" and #value.file_version == 4, "Four file version components required")
	for _, number in ipairs(value.file_version) do
		assert(type(number) == "number" and number >= 0 and number <= 65535 and number % 1 == 0, "Invalid file version component")
	end
	assert(type(value.prerelease) == "boolean", "Prerelease flag required")
	return value
end

local function git_output(command)
	local sink = os.host() == "windows" and " 2>nul" or " 2>/dev/null"
	local process = io.popen("git " .. command .. sink, "r")
	if not process then return nil end
	local result = process:read("*a")
	local ok = process:close()
	if not ok then return nil end
	return result and result:gsub("%s+$", "")
end

local function write_if_changed(filename, content)
	local old = io.open(filename, "rb")
	if old then
		local previous = old:read("*a")
		old:close()
		if previous == content then return end
	end
	os.mkdir(path.getdirectory(filename))
	local file = assert(io.open(filename, "wb"))
	file:write(content)
	file:close()
end

local function git_value(command, fallback)
	local value = git_output(command)
	return value and value ~= "" and value or fallback
end

newaction {
	trigger = "version",
	description = "Print the product version from version.json.",
	onWorkspace = function()
		print(release_version().name)
	end
}

newaction {
	trigger = "generate-buildinfo",
	description = "Generate release version and optional Git provenance headers.",
	onWorkspace = function(wks)
		local release = release_version()
		local commit = git_value("rev-parse --verify HEAD", "unknown")
		local describe = git_value("describe --tags --dirty --always", "unknown")
		local branch = git_value("branch --show-current", "unknown")
		local tag = git_value("describe --tags --abbrev=0", "")
		local status = git_output("status --porcelain")
		local dirty = status == "" and 0 or 1
		local lines = {
			"/* Automatically generated by premake5 from version.json. Do not edit. */",
			"#define GIT_DESCRIBE " .. cstrquote(describe),
			"#define GIT_DIRTY " .. dirty,
			"#define GIT_HASH " .. cstrquote(commit),
			"#define GIT_TAG " .. cstrquote(tag),
			"#define GIT_BRANCH " .. cstrquote(branch),
			"#define VERSION_PRODUCT_RC " .. table.concat(release.file_version, ","),
			"#define VERSION_FILE_RC " .. table.concat(release.file_version, ","),
			"#define VERSION_PRODUCT " .. cstrquote(release.name),
			"#define VERSION_FILE " .. cstrquote(release.name),
			"#define VERSION VERSION_PRODUCT",
			"#define SHORTVERSION VERSION_PRODUCT",
		}
		if release.prerelease then table.insert(lines, "#define PRERELEASE 1") end
		write_if_changed(path.join(wks.location, "src/version.h"), table.concat(lines, "\n") .. "\n")
		write_if_changed(path.join(wks.location, "src/version.hpp"), "#pragma once\n#include \"version.h\"\n")
		write_if_changed(path.join(wks.location, "version.txt"), commit .. "\n")
		print("Product version: " .. release.name)
	end
}
